name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  sidebarx: ^0.17.1
  hawk_fab_menu: ^1.2.0
  dio: ^5.8.0+1
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  convex_bottom_bar: ^3.2.0
  flutter_rating_bar: ^4.0.1
  shimmer: ^2.0.0
  cached_network_image: ^3.4.1
  youtube_player_iframe: ^5.2.1 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fondo.jpg
    - assets/logo.png
    - assets/boton.json
    - assets/loading.json
    - assets/loading_api.gif